"use client";

import { useState, useTransition } from "react";

import { clientApi } from "@/lib/client-api";
import { GhostNumeral } from "@/components/ui/GhostNumeral";
import { SectionReveal } from "@/components/ui/SectionReveal";
import type { CustomerInput } from "@/lib/types";

type Props = {
  customer: CustomerInput;
  surname: string;
  probability: number;
  explanation: string;
};

export function Pitch({ customer, surname, probability, explanation }: Props) {
  const [email, setEmail] = useState<string>("");
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function generate() {
    setError(null);
    startTransition(async () => {
      try {
        const r = await clientApi.email(customer, surname, probability, explanation);
        setEmail(r.text);
      } catch (e) {
        setError(e instanceof Error ? e.message : "Failed to generate.");
      }
    });
  }

  return (
    <SectionReveal>
    <section className="relative py-12">
      <div className="mb-3 border-t border-ink/80" />
      <div className="mb-3 border-t border-ink/80" />
      <GhostNumeral className="left-0 top-2 text-[180px] italic sm:text-[220px]">
        V
      </GhostNumeral>

      <div className="text-[10px] uppercase tracking-[0.32em] text-mute">
        The pitch <span className="text-terra">/ Section V</span>
      </div>
      <h2 className="font-display mt-2 max-w-[26ch] text-[32px] tracking-[-0.01em] sm:text-[40px]">
        The letter the model would write.
      </h2>
      <p className="mt-3 max-w-[60ch] text-[15px] leading-[1.6] text-graph">
        Pressing &ldquo;Draft retention email&rdquo; sends the prediction and a
        short explanation to a small language model and asks for a letter to
        keep this customer.
      </p>

      <div className="mt-8 grid grid-cols-1 gap-8 lg:grid-cols-[1fr_auto_2fr] lg:items-start">
        <div className="space-y-3">
          <button
            type="button"
            onClick={generate}
            disabled={pending}
            className="inline-flex items-center gap-2 border border-ink bg-cream px-4 py-2 text-sm transition-colors hover:bg-ink hover:text-cream disabled:opacity-50"
          >
            {pending ? "Drafting..." : email ? "Re-draft retention email" : "Draft retention email"}
          </button>
          {error && <div className="text-[12px] text-terra">{error}</div>}
          <p className="max-w-[36ch] text-[12px] italic text-mute">
            Generated by Llama 4 Scout via Groq. Treat as a draft.
          </p>
        </div>

        <div className="hidden lg:block lg:h-full lg:border-l lg:border-rule" aria-hidden />

        <article className="min-h-[220px] border-l-2 border-rule pl-6">
          <div className="mb-3 grid grid-cols-[auto_1fr] gap-x-3 gap-y-0.5 text-[10px] uppercase tracking-[0.22em] text-mute">
            <span>From</span>
            <span className="text-graph">Retention desk</span>
            <span>Re</span>
            <span className="text-graph">{surname}, renewal of relationship</span>
          </div>
          {email ? (
            <div className="font-display whitespace-pre-line text-[18px] leading-[1.7] text-ink">
              {email}
            </div>
          ) : (
            <div className="font-display text-[18px] italic leading-[1.7] text-mute">
              No draft yet. The page is intentionally quiet until you ask for
              one. Sending the prompt to the model takes a moment and costs a
              small amount of tokens.
            </div>
          )}
        </article>
      </div>
    </section>
    </SectionReveal>
  );
}
